// ============================================================================
// BrokerOS — Email Marketing Provider Catalog
// ============================================================================

export const EMAIL_PROVIDERS = {
  SYSTEM_DEFAULT: {
    id: 'SYSTEM_DEFAULT',
    type: 'SYSTEM_DEFAULT',
    name: 'BrokerOS Managed SES',
    badge: 'Recommended',
    description: 'Pre-configured AWS SES with dedicated IP warming & 99.4% inbox deliverability.',
    color: '#7C3AED',
    docsUrl: 'https://docs.aws.amazon.com/ses/',
    fields: [],
    requiresCredentials: false,
  },
  AWS_SES: {
    id: 'AWS_SES',
    type: 'AWS_SES',
    name: 'Amazon Simple Email Service (SES)',
    badge: 'High Volume',
    description: 'Connect your own AWS SES account for cost-effective ($0.10/1k) mass email dispatches.',
    color: '#FF9900',
    docsUrl: 'https://docs.aws.amazon.com/ses/',
    fields: [
      { key: 'awsAccessKeyId', label: 'AWS Access Key ID', type: 'text', placeholder: 'AKIAIOSFODNN7EXAMPLE', required: true },
      { key: 'awsSecretKey', label: 'AWS Secret Access Key', type: 'password', placeholder: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY', required: true },
      { key: 'awsRegion', label: 'AWS Region', type: 'text', placeholder: 'ap-south-1', required: true },
      { key: 'fromEmail', label: 'Verified Sender Email', type: 'email', placeholder: 'sales@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Skyline Sales Team', required: true },
    ],
    requiresCredentials: true,
  },
  SENDGRID: {
    id: 'SENDGRID',
    type: 'SENDGRID',
    name: 'Twilio SendGrid',
    badge: 'Analytics',
    description: 'Industry standard for transactional & marketing automation with built-in spam scoring.',
    color: '#0052FF',
    docsUrl: 'https://docs.sendgrid.com/api-reference',
    fields: [
      { key: 'apiKey', label: 'SendGrid API Key', type: 'password', placeholder: 'SG.xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'fromEmail', label: 'Verified Sender Email', type: 'email', placeholder: 'campaigns@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Skyline Luxury Residences', required: true },
    ],
    requiresCredentials: true,
  },
  BREVO: {
    id: 'BREVO',
    type: 'BREVO',
    name: 'Brevo (formerly Sendinblue)',
    badge: 'GDPR / India',
    description: 'European & Asian cloud delivery with strict data isolation & dedicated IP support.',
    color: '#00B96B',
    docsUrl: 'https://developers.brevo.com/',
    fields: [
      { key: 'apiKey', label: 'Brevo v3 API Key', type: 'password', placeholder: 'xkeysib-xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'fromEmail', label: 'Verified Sender Email', type: 'email', placeholder: 'info@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Skyline Realty', required: true },
    ],
    requiresCredentials: true,
  },
  MAILCHIMP: {
    id: 'MAILCHIMP',
    type: 'MAILCHIMP',
    name: 'Mailchimp Transactional (Mandrill)',
    badge: 'Legacy',
    description: 'Enterprise transactional email delivery engine with extensive merge-tag template support.',
    color: '#FFE01B',
    docsUrl: 'https://mailchimp.com/developer/transactional/',
    fields: [
      { key: 'apiKey', label: 'Mandrill API Key', type: 'password', placeholder: 'md-xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'fromEmail', label: 'Sender Email', type: 'email', placeholder: 'sales@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Sales Gallery', required: true },
    ],
    requiresCredentials: true,
  },
  MAILGUN: {
    id: 'MAILGUN',
    type: 'MAILGUN',
    name: 'Mailgun (by Sinch)',
    badge: 'Enterprise REST',
    description: 'Powerful developer-first email infrastructure with built-in SPF/DKIM verification and webhooks.',
    color: '#F06B00',
    docsUrl: 'https://documentation.mailgun.com/docs/mailgun/api-reference/',
    fields: [
      { key: 'apiKey', label: 'Mailgun Private API Key', type: 'password', placeholder: 'key-xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'mailgunDomain', label: 'Sending Domain', type: 'text', placeholder: 'mail.yourbrokerage.com', required: true },
      { key: 'mailgunRegion', label: 'Region (US or EU)', type: 'text', placeholder: 'US', required: false },
      { key: 'fromEmail', label: 'Sender Email', type: 'email', placeholder: 'sales@mail.yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Brokerage Sales', required: true },
    ],
    requiresCredentials: true,
  },
  GMAIL: {
    id: 'GMAIL',
    type: 'GMAIL',
    name: 'Gmail / Google Workspace',
    badge: 'Deliverability',
    description: 'Send directly through authentic Google Workspace mailboxes with high inbox placement.',
    color: '#EA4335',
    docsUrl: 'https://developers.google.com/gmail/api',
    fields: [
      { key: 'googleAppPassword', label: 'Google App Password / SMTP Key', type: 'password', placeholder: 'xxxx xxxx xxxx xxxx', required: true },
      { key: 'fromEmail', label: 'Google Workspace Email', type: 'email', placeholder: 'agent@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Agent Name', required: true },
      { key: 'googleClientId', label: 'OAuth Client ID (Optional)', type: 'text', placeholder: 'xxxx.apps.googleusercontent.com', required: false },
      { key: 'googleClientSecret', label: 'OAuth Client Secret (Optional)', type: 'password', placeholder: 'GOCSPX-xxxxxxxx', required: false },
      { key: 'googleRefreshToken', label: 'OAuth Refresh Token (Optional)', type: 'password', placeholder: '1//xxxxxxxx', required: false },
    ],
    requiresCredentials: true,
  },
  OUTLOOK: {
    id: 'OUTLOOK',
    type: 'OUTLOOK',
    name: 'Microsoft 365 / Outlook',
    badge: 'Microsoft 365',
    description: 'Enterprise Microsoft Graph email dispatch directly via corporate Exchange mailboxes.',
    color: '#0078D4',
    docsUrl: 'https://learn.microsoft.com/en-us/graph/api/user-sendmail',
    fields: [
      { key: 'microsoftClientId', label: 'Azure Client ID', type: 'text', placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', required: true },
      { key: 'microsoftClientSecret', label: 'Azure Client Secret', type: 'password', placeholder: 'xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'microsoftTenantId', label: 'Azure Tenant ID', type: 'text', placeholder: 'common or Tenant GUID', required: true },
      { key: 'microsoftRefreshToken', label: 'OAuth Refresh Token', type: 'password', placeholder: '0.AAAAxxxxxxxx', required: true },
      { key: 'fromEmail', label: 'Microsoft 365 Mailbox', type: 'email', placeholder: 'corporate@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Executive Office', required: true },
    ],
    requiresCredentials: true,
  },
  CONSTANT_CONTACT: {
    id: 'CONSTANT_CONTACT',
    type: 'CONSTANT_CONTACT',
    name: 'Constant Contact',
    badge: 'Broadcast',
    description: 'Broadcast email engine with comprehensive contact management and campaign metrics.',
    color: '#1856C3',
    docsUrl: 'https://developer.constantcontact.com/api_reference/index.html',
    fields: [
      { key: 'constantContactApiKey', label: 'API Key / Client ID', type: 'password', placeholder: 'xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'constantContactSecret', label: 'App Secret', type: 'password', placeholder: 'xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'constantContactRefreshToken', label: 'OAuth Refresh Token', type: 'password', placeholder: 'xxxxxxxxxxxxxxxxxxxx', required: true },
      { key: 'fromEmail', label: 'Verified Sender Email', type: 'email', placeholder: 'news@yourbrokerage.com', required: true },
      { key: 'fromName', label: 'Default Sender Name', type: 'text', placeholder: 'Brokerage Updates', required: true },
    ],
    requiresCredentials: true,
  },
  MULTI_PROVIDER: {
    id: 'MULTI_PROVIDER',
    type: 'MULTI_PROVIDER',
    name: 'Distributed Multi-Provider',
    badge: 'Multi-Stream',
    description: 'Dynamic load distribution across multiple verified sender domains and engines.',
    color: '#8B5CF6',
    docsUrl: '',
    fields: [],
    requiresCredentials: false,
  },
} as const;

export const EMAIL_PROVIDERS_LIST = Object.values(EMAIL_PROVIDERS);

export const EMAIL_PROVIDER_PRICING_ESTIMATES = {
  SYSTEM_DEFAULT: { costPer1kUSD: 0.10, costPer1kINR: 9.50, label: 'BrokerOS SES Dedicated (~$0.10/1k)' },
  AWS_SES: { costPer1kUSD: 0.10, costPer1kINR: 9.50, label: 'AWS SES Direct (~$0.10/1k)' },
  SENDGRID: { costPer1kUSD: 0.15, costPer1kINR: 14.28, label: 'Twilio SendGrid (~$0.15/1k)' },
  BREVO: { costPer1kUSD: 0.12, costPer1kINR: 11.43, label: 'Brevo Cloud (~$0.12/1k)' },
  MAILCHIMP: { costPer1kUSD: 0.20, costPer1kINR: 19.05, label: 'Mailchimp Mandrill (~$0.20/1k)' },
  MAILGUN: { costPer1kUSD: 0.15, costPer1kINR: 14.28, label: 'Mailgun Infrastructure (~$0.15/1k)' },
  GMAIL: { costPer1kUSD: 0.00, costPer1kINR: 0.00, label: 'Google Workspace Direct ($0/included)' },
  OUTLOOK: { costPer1kUSD: 0.00, costPer1kINR: 0.00, label: 'Microsoft 365 Direct ($0/included)' },
  CONSTANT_CONTACT: { costPer1kUSD: 0.20, costPer1kINR: 19.05, label: 'Constant Contact Broadcast (~$0.20/1k)' },
  MULTI_PROVIDER: { costPer1kUSD: 0.12, costPer1kINR: 11.40, label: 'Distributed Multi-Engine (~$0.12/1k)' },
} as const;

export const PROVIDER_THROTTLE_LIMITS = {
  AWS_SES: { maxPerSecond: 25, delayMs: 10 },
  SYSTEM_DEFAULT: { maxPerSecond: 25, delayMs: 10 },
  SENDGRID: { maxPerSecond: 25, delayMs: 15 },
  BREVO: { maxPerSecond: 15, delayMs: 35 },
  MAILCHIMP: { maxPerSecond: 20, delayMs: 20 },
  MAILGUN: { maxPerSecond: 40, delayMs: 10 },
  GMAIL: { maxPerSecond: 10, delayMs: 50 },
  OUTLOOK: { maxPerSecond: 15, delayMs: 35 },
  CONSTANT_CONTACT: { maxPerSecond: 20, delayMs: 25 },
  MULTI_PROVIDER: { maxPerSecond: 50, delayMs: 10 },
} as const;

export const DELIVERABILITY_WARMUP_SCHEDULE = {
  STAGE_1: { days: '1-3', maxDaily: 300, label: 'Warmup Stage 1 (300/day)' },
  STAGE_2: { days: '4-7', maxDaily: 750, label: 'Warmup Stage 2 (750/day)' },
  STAGE_3: { days: '8-14', maxDaily: 2000, label: 'Warmup Stage 3 (2,000/day)' },
  MATURE: { days: '15+', maxDaily: 10000, label: 'Mature Domain (10,000+/day)' },
} as const;

export const ALLOCATION_MODES = {
  AUTO_EVEN: 'AUTO_EVEN',
  CUSTOM_WEIGHTED: 'CUSTOM_WEIGHTED',
} as const;
